export const EMAIL_PROVIDER = 'EMAIL_PROVIDER';
export const SMS_PROVIDER = 'SMS_PROVIDER';
export const PUSH_PROVIDER = 'PUSH_PROVIDER';
export const WHATSAPP_PROVIDER = 'WHATSAPP_PROVIDER';
export const SLACK_PROVIDER = 'SLACK_PROVIDER';
export const UPLOAD_PROVIDER = 'UPLOAD_PROVIDER';
